import { CommonModule } from '@angular/common';
import {
  ChangeDetectionStrategy,
  Component,
  EventEmitter,
  forwardRef,
  Inject,
  OnDestroy,
  OnInit,
  Output,
  ViewEncapsulation
} from '@angular/core';
import { InputComponent } from '@shared/components/input/input.component';
import {
  BaseWidget,
  NgAisInstantSearch,
  NgAisModule
} from 'angular-instantsearch';
import { connectSearchBox } from 'instantsearch.js/es/connectors';
import { EMPTY, filter, map, Observable, scan, tap } from 'rxjs';

// Generated by https://quicktype.io

export interface SearchHit {
  objectID: string;
  title: string;
  start: string;
  end: string;
  tags: string[];
  session: {
    videoId: string;
    title: string;
    subtitle: string;
    tags: string[];
    category: string;
  };
}

@Component({
  selector: 'app-search-widget',
  template: `<app-input
      [value]="state.query"
      [delay]="200"
      (query)="onQuery($event)"
    ></app-input>

    <ng-container *ngIf="results$ | async as results">
      <div class="drop-down" *ngIf="!!state.query">
        <ng-template #noResults> No results. </ng-template>
        <ng-container *ngIf="results.size; else noResults">
          <table>
            <tr *ngFor="let result of results | keyvalue">
              <td class="title">
                <h3>{{ result.key }}</h3>
              </td>
              <td>
                <div
                  class="hit"
                  *ngFor="let hit of result.value"
                  (click)="onSearchHit(hit)"
                >
                  <ais-highlight attribute="title" [hit]="hit"></ais-highlight>
                </div>
              </td>
            </tr>
          </table>
        </ng-container>
        <div class="algolia">
          <img src="/assets/algolia.svg" alt="Search by Algilia" />
        </div>
      </div>
    </ng-container> `,
  styles: [
    `
      .drop-down {
        position: absolute;
        margin-top: 5px;
        padding: 12px;
        border-radius: 5px;
        color: var(--body-color);
        border: 0;
        transition: background 0.3s, box-shadow 0.3s;
        background-color: var(--bg-transparent);
        opacity: 1;
      }

      .drop-down:before {
        content: '';
        background-color: transparent;
        border-right: 8px solid transparent;
        position: absolute;
        border-left: 8px solid transparent;
        border-bottom: 8px solid var(--bg-transparent);
        border-top: 8px solid transparent;
        top: -15px;
        right: 18px;
      }

      .title {
        h3 {
          padding: 5px 5px;
          margin: 0;
          margin-right: 15px;
        }
        vertical-align: top;
      }

      .hit {
        padding: 5px 5px;
        cursor: pointer;
      }

      .ais-Highlight-highlighted {
        color: var(--primary-color) !important;
      }

      .algolia {
        margin-top: 10px;
        text-align: right;
        img {
          height: 20px;
        }
      }
    `
  ],
  changeDetection: ChangeDetectionStrategy.OnPush,
  encapsulation: ViewEncapsulation.None,
  standalone: true,
  imports: [InputComponent, NgAisModule, CommonModule]
})
export class SearchWidgetComponent
  extends BaseWidget
  implements OnInit, OnDestroy
{
  @Output() searchHit = new EventEmitter<SearchHit>();
  parentIndex: any;
  results$: Observable<Map<string, any[]>> = EMPTY;
  state: {
    query: string;
    nbHits: number;
    refine: (value: string) => void;
  } = { query: '', nbHits: 0, refine: () => {} };
  constructor(
    @Inject(forwardRef(() => NgAisInstantSearch))
    public instantSearchInstance: NgAisInstantSearch
  ) {
    super('SearchBox');
    this.createWidget(connectSearchBox as any, {});
  }

  ngOnInit() {
    super.ngOnInit();
    this.results$ = this.instantSearchInstance.change.pipe(
      filter(() => !!this.state.query),
      map(({ results }: { results: any }) => {
        const groupedBySession: Map<string, any[]> = (
          results?.hits || []
        ).reduce((grouped: Map<string, any[]>, hit: any) => {
          const titles = grouped.get(hit.session.title) || [];
          if (!titles.length) {
            grouped.set(hit.session.title, titles);
          }
          titles.push(hit);
          return grouped;
        }, new Map<string, any[]>());
        return groupedBySession;
      })
    );
  }

  onQuery(query: string) {
    this.state.refine(query);
  }

  onSearchHit(hit: SearchHit) {
    this.searchHit.emit(hit);
    this.state.query = '';
  }
}
