import {
  ChangeDetectionStrategy,
  Component,
  EventEmitter,
  forwardRef,
  Inject,
  OnDestroy,
  OnInit,
  Output,
  ViewEncapsulation
} from '@angular/core';
import { BaseWidget, NgAisInstantSearch } from 'angular-instantsearch';
import { connectSearchBox } from 'instantsearch.js/es/connectors';
import { EMPTY, filter, map, Observable, scan, tap } from 'rxjs';

// Generated by https://quicktype.io

export interface SearchHit {
  objectID: string;
  title: string;
  start: string;
  end: string;
  tags: string[];
  session: {
    videoId: string;
    title: string;
    subtitle: string;
    tags: string[];
    category: string;
  };
}

@Component({
  selector: 'app-search-widget',
  templateUrl: './search-widget.component.html',
  styleUrls: ['./search-wigdet.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush,
  encapsulation: ViewEncapsulation.None
})
export class SearchWidgetComponent
  extends BaseWidget
  implements OnInit, OnDestroy
{
  @Output() searchHit = new EventEmitter<SearchHit>();
  parentIndex: any;
  results$: Observable<Map<string, any[]>> = EMPTY;
  state: {
    query: string;
    nbHits: number;
    refine: (value: string) => void;
  } = { query: '', nbHits: 0, refine: () => {} };
  constructor(
    @Inject(forwardRef(() => NgAisInstantSearch))
    public instantSearchInstance: NgAisInstantSearch
  ) {
    super('SearchBox');
    this.createWidget(connectSearchBox as any, {});
  }

  ngOnInit() {
    super.ngOnInit();
    this.results$ = this.instantSearchInstance.change.pipe(
      filter(() => !!this.state.query),
      map(({ results }: { results: any }) => {
        const groupedBySession: Map<string, any[]> = (
          results?.hits || []
        ).reduce((grouped: Map<string, any[]>, hit: any) => {
          const titles = grouped.get(hit.session.title) || [];
          if (!titles.length) {
            grouped.set(hit.session.title, titles);
          }
          titles.push(hit);
          return grouped;
        }, new Map<string, any[]>());
        console.log(groupedBySession);
        return groupedBySession;
      })
    );
  }

  onQuery(query: string) {
    this.state.refine(query);
  }

  onSearchHit(hit: SearchHit) {
    this.searchHit.emit(hit);
    this.state.query = '';
  }
}
